language: python
sudo: false
python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - AIOHTTP_VERSION=3.6.2
  - AIOHTTP_VERSION=2.3.10

install:
  - python setup.py install
  - pip install -U pip
  - pip install -r requirements-dev.txt
  - pip install -U codecov
  - pip install -q aiohttp==$AIOHTTP_VERSION

script:
  - make cov

after_success:
  - codecov

deploy:

  # Deploy to PyPI
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWD
  distributions: "sdist"
  on:
    tags: true
    python: 3.7
    condition: $AIOHTTP_VERSION = 3.6.2

#  - provider: script
#    script: deploy/pypi.sh
#    skip_cleanup: true
#    on:
#      branch: master
